#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.10.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - nodel_modules
          key: v1-dependencies-{{checksum "package.json"}}
      - run: yarn test